[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
battle = "FpiJ4hDruR6oj5Eeawk4kYUKzzRP8nRbVZYwfuSgCtKF"
cash_out = "5Na7qMLrgu24ACdb5zeGqpzWw2GgZQ2fVS8XxKv3d7r5"
init_map = "36K9kUECFsZrnsDeuD49biyHrtwptL48TfCgDf689h7H"
init_player = "71i58jXe7Hv6yBzMH13gvMP2sLuVZ2AMVJKkgTCS2Fzu"
init_prizepool = "ESGndWFErYWf68ASK75vctW6EvHvWHemHcQSmrjdgCHN"
map = "H55UcuGxCmpH1cE6Tsm8EUYVdQz99AHhwBN551jUW8a1"
mine = "C58xgk3FQsJKnuHwkmzYJWASK1U8NnpBSWA1Bx22rCwD"
miner_war = "ETspbWudbuMGNh3d5EGK9oEFi1zrHRjy5d7ic4haYAwA"
pay_entry = "GQCGW6hJZD7Ar8JPZqnGMKrbe98inGLDfcj3roGUimBd"
player = "714kBkMzu7e4ZNcmVKLBUYjJdo3YBfUQvtWwzucipB7b"
prizepool = "9vvBKfn1FCcJg4U3zywMqnUXFvaLo5ZMFVWsVUPp5zz5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/*", "programs-ecs/components/*", "programs-ecs/systems/*"]

[scripts]
_test = "bolt test --skip-build --skip-local-validator --skip-deploy"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "WorLD15A7CrDwLcLy4fRqtaTb9fbd8o8iqiEMUDse2n"
program = "tests/fixtures/world.so"
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://rpc.magicblock.app/devnet/"
ledger = ".bolt/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "EHLkWwAT9oebVv9ht3mtqrvHhRVMKrt54tF3MfHTey2K"
filename = "tests/fixtures/registry.json"
