[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
<<<<<<< HEAD
battle = "HEqNqfq7WKJu5xa6qjdsMFjWe7bu5qr1L7Cr5ExsPSBL"
cash_out = "A4qZibJ3rUGd9izgHXX5tapbRbhbT7Xu8u29RzKsuTp8"
init_map = "McinrqX4S1BFPmvSQvWfwYrLer8e4sQaU2xvaSwpFqb"
init_player = "GPRFeHp9j5miMk5A5YXCcKBf7eCGAt73UR5Zb4c126ys"
init_prizepool = "4eHFKWZF3pzDPcnVgBmUQaivbT1WHxUBCcZ5aRUjMUPS"
map = "HHAJcQfjE8YTi8g4aFJot4AMdoWCzHGzFasGC4PZ5mnH"
mine = "4n8unqB9VVCBKx6nWwJKtU9MSSvm7AooKcF3H3dUkNJz"
miner_war = "2jMV4AYNBLzygv4SzZyyAVxHqNBDFSvhSd3GYWSrnptY"
pay_entry = "55ACnfWJWMsJhZzasi5hX5kfhJGymRBWKuk9MKaiooJg"
player = "7e8EGdmfGvcQYhcdonVLXZsBtqs3ajkk5TbqhwgnJvRy"
prizepool = "HrY7PavGixzsDPGic6tehAcsa2G7DYew3Q4YsK8BkDFw"
=======
battle = "FpiJ4hDruR6oj5Eeawk4kYUKzzRP8nRbVZYwfuSgCtKF"
init_map = "36K9kUECFsZrnsDeuD49biyHrtwptL48TfCgDf689h7H"
init_player = "71i58jXe7Hv6yBzMH13gvMP2sLuVZ2AMVJKkgTCS2Fzu"
init_prizepool = "ESGndWFErYWf68ASK75vctW6EvHvWHemHcQSmrjdgCHN"
map = "H55UcuGxCmpH1cE6Tsm8EUYVdQz99AHhwBN551jUW8a1"
mine = "C58xgk3FQsJKnuHwkmzYJWASK1U8NnpBSWA1Bx22rCwD"
miner_war = "ETspbWudbuMGNh3d5EGK9oEFi1zrHRjy5d7ic4haYAwA"
pay_entry = "GQCGW6hJZD7Ar8JPZqnGMKrbe98inGLDfcj3roGUimBd"
player = "714kBkMzu7e4ZNcmVKLBUYjJdo3YBfUQvtWwzucipB7b"
prizepool = "9vvBKfn1FCcJg4U3zywMqnUXFvaLo5ZMFVWsVUPp5zz5"
>>>>>>> 41eb9cab61d90567e1b68439d333f94866ffa023

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/*", "programs-ecs/components/*", "programs-ecs/systems/*"]

[scripts]
_test = "bolt test --skip-build --skip-local-validator --skip-deploy"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "WorLD15A7CrDwLcLy4fRqtaTb9fbd8o8iqiEMUDse2n"
program = "tests/fixtures/world.so"
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://rpc.magicblock.app/devnet/"
ledger = ".bolt/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "EHLkWwAT9oebVv9ht3mtqrvHhRVMKrt54tF3MfHTey2K"
filename = "tests/fixtures/registry.json"
